#  To run Postgres + Redis + API + Worker

version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webhookdb
        #    ports:
        # - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  redis:
    image: redis:latest
      # ports:
      #  - "6379:6379"

  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/webhookdb
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: npm run worker
    environment:
      DATABASE_URL: postgres://user:password@db:5432/webhookdb
      REDIS_URL: redis://redis:6379
      OPENAI_API_KEY: ${OPENAI_API_KEY}  
    depends_on:
      - db
      - redis

volumes:
  db-data:
